# Generated by Django 5.0.1 on 2024-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=50)),
                ('mechanic', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
